### ISSUE TITLE
Add support for `java.time` (Java 8 date/time) types

### ISSUE THREAD

**Issue by sebastian-zero** [FasterXML/jackson-jr#100]
We found that jackson-jr is great in cases where small library size and fast initialization time is important. We use it in Android apps and AWS Lambdas. But one thing that is missing is support for date/time types as specified in JSR-310 specification.

I understand that this is currently only possible by implementing custom ValueReaders/ValueWriters. The documentation points to a blog post with some Groovy code that is not available anymore and can only be found through the [web archive](https://web.archive.org/web/20210805053523/https://www.andersaaberg.dk/2020/enable-support-for-java-time-with-jackson-jr/). 

Please consider adding support for Java 8 date/time types to jackson-jr, e.g. though an additional library/module that provides the required ValueReaders and ValueWriters.

**Comment by cowtowncoder** [comment]
This sounds like a great idea @sebastian-zero! Also happy to hear this library works for one of the cases I intended it to (well, actually 2! :) ).

Unfortunately I probably won't have time to work on this directly (even if starting with the linked-to article which sounds like a great starting point!), but I hope that someone else could -- and if so I'll do my best to help them get additional Extension merged.
I prioritize work helping get PRs merged above almost everything else so if anyone is interested in tackling this, please do!

**Comment by Shounaks** [comment]
Sounds like a easy contribution. How do I start?

**Comment by cowtowncoder** [comment]
Initial implementation supporting just `LocalDateTime` now merged in for 2.17.
