### ISSUE TITLE
Cannot deserialize `byte[]` from JSON `null` value

### ISSUE THREAD

**Issue by reed53** [FasterXML/jackson-jr#107]
Hello,
I ran into a bug today that I don't see a workaround for.
If I have an object like so:
```
  @Setter
  @Getter
  public static class ObjectWithByteArray {
      private byte[] arr;
  }
```

and I try to deserialize `"{\"arr\":null}"`, I get the following error:
```
com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not VALUE_STRING or VALUE_EMBEDDED_OBJECT, can not access as binary
 at [Source: (String)"{"arr":null}"; line: 1, column: 12]
```

I then tried to implement a custom reader for byte arrays to work around this issue, however it seems like the error occurred before the reader has access to the value.

**Comment by cowtowncoder** [comment]
Could you please include a full reproduction, without using `@Setter` / `@Getter` annotations, and specifically include call you use for `jackson-jr`. Code snippets do not necessarily allow us to reproduce exact issue and we end up wasting time figuring out exact details otherwise.

**Comment by reed53** [comment]
No worries! Here is a java program that when executed, reproduces the bug:
import com.fasterxml.jackson.jr.ob.JSON;

```
import java.io.IOException;

public class Test {

    public static void main(String[] args) throws IOException {
        var serialized = "{\"arr\":null}";
        var mapper = JSON.builder().build();

        var deserialized = mapper.beanFrom(ObjectWithByteArray.class, serialized);

        System.out.println(deserialized);
    }

    public static class ObjectWithByteArray {
        private byte[] arr;

        public byte[] getArr() {
            return arr;
        }

        public void setArr(byte[] arr) {
            this.arr = arr;
        }
    }
}
```

**Comment by cowtowncoder** [comment]
Excellent, thank you @reed53 ! Definitely looks like a bug.

**Comment by cowtowncoder** [comment]
Fixed for 2.15(.3) / 2.16(.0).

**Comment by reed53** [comment]
Do you know how long it may be until a release?

**Comment by cowtowncoder** [comment]
@reed53 Unfortunately hard to predict, BUT, I am hoping to get first 2.16 release candidate out within this or next week. And would make sense to release 2.15.3 at around same time. So I think it can go out within 2 weeks if and when I find time (release takes 2-4 hours for the whole Jackson set)
