### ISSUE TITLE
Can jr ignore some property name where building JSON string ?

### ISSUE THREAD

**Issue by shawnye** [FasterXML/jackson-jr#14]
I think It is better if there is method  like 'excludeProperties()' or 'ignoreProperties()'  in com.fasterxml.jackson.jr.ob.JSON.

The method mentioned above can simplify jackson databind counterpart :
<code>
objectMapper.setPropertyNamingStrategy(new PropertyNamingStrategy() {
});
</code>
That is also jr's philosophy,isn't it :) 
Thank you

**Comment by cowtowncoder** [comment]
I think #32 can cover this, adding building blocks to achieve this.
