### ISSUE TITLE
JDK17 Record deserialization should work with default settings (no need for `JSON.Feature.USE_FIELD_MATCHING_GETTERS`)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-jr#155]
(off-shoot of #149 )

While #148 adds support for deserializing Java (17) records, it requires explicit enabling of `JSON.Feature.USE_FIELD_MATCHING_GETTERS` (as per tests that now run).
But this should not be needed; code should automatically apply this setting for Record types.

**Comment by cowtowncoder** [comment]
@TomaszGaweda could you help fix this issue?

**Comment by TomaszGaweda** [comment]
I will take a look, but probably tomorrow :)

**Comment by cowtowncoder** [comment]
@TomaszGaweda thanks! Looks like #154 lead to PR #156 which _Should_ fix this but... somehow doesn't. But hopefully we'll figure out quickly.

**Comment by cowtowncoder** [comment]
Fixed via #156
