### ISSUE TITLE
Android Studio problem with reserved keyword in package name

### ISSUE THREAD

**Issue by mata1** [FasterXML/jackson-jr#17]
Because there is a package named "private" in com.fasterxml.jackson.jr, which is reserved keyword, Android Studio IDE is showing errors. Code compiles normally.

For example:
try {
    // error: unhandled exception: JSONObjectException
    LockAccess[] la = JSON.std.arrayOfFrom(LockAccess.class, response.toString());
} catch (Exception e) {
    e.printStackTrace();
}
and:
try {
    LockAccess[] la = JSON.std.arrayOfFrom(LockAccess.class, response.toString());
} catch (JSONObjectException e) {
    // error: incompatible types, required: Throwable, found: JSONObjectException
    e.printStackTrace();
}

There is a similar problem described here: http://stackoverflow.com/questions/14104956/unable-to-catch-jsonmappingexception

**Comment by Enuratique** [comment]
I too am having the exact same problem described by @mata1. Code compiles fine, the Android Studio 1.X IDE is complaining about it though... Kind of frustrating. I wish I could suppress the IDE's error message.

**Comment by cowtowncoder** [comment]
Ok. While it seems to me that IDE is wrong, due to numerous reports it seems easier to just change the package name to "private_", and hope users are not careless enough to import anything from that package. Will go in 2.7.0 final.

**Comment by gvan** [comment]
I use jarjar program https://code.google.com/p/jarjar/ to fix this problem

just create file with next rules: rule com.fasterxml.jackson.jr.private** com.fasterxml.jackson.jr.pritate_@1

and run from command line: java -jar jarjar-1.4.jar process jar_rules jackson-jr-all-2.6.3.jar jackson-jr-all-2.6.4.jar

so now the library works in my Android Studio project
