### ISSUE TITLE
Record deserialisation with instance methods fails

### ISSUE THREAD

**Issue by Giovds** [FasterXML/jackson-jr#172]
The deserialisation now works for plain records, as fixed with #167.
However, I've slightly changed my implementation of my record to move some logic for calculating the time into a record instance method. Deserialisation with instance methods fails, as it tries to access a field that does not exist.

The `final List<POJODefinition.Prop> rawProps = beanDef.getProperties();` contains a `dateTime` property which is declared in the record as instance method. When you get the `FoundDependency.class` declared fields it is not there, as it is a derived value and not a constructor parameter. It does however work (as expected) for static instance methods.

Test case slightly modified to replicate the issue:
```java
public class RecordDeser167Test extends TestCase
{
    record FoundDependency(String id, String g, String a, String v, long timestamp) {
        public LocalDate getDateTime() {
            return Instant.ofEpochMilli(timestamp).atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        }
    }

    // [jackson-jr#167]
    public void testRecordDeserOrder167() throws Exception
    {
        final String input = """
            {
              "id": "org.apache.maven:maven-core:3.9.8",
              "g": "org.apache.maven",
              "a": "maven-core",
              "v": "3.9.8",
              "p": "jar",
              "timestamp": 1718267050000,
              "ec": [
                "-cyclonedx.json",
                "-sources.jar",
                "-cyclonedx.xml",
                ".pom",
                "-javadoc.jar",
                ".jar"
              ],
              "tags": [
                "core",
                "maven",
                "classes"
              ]
            }
            """;
        final var expected = new FoundDependency("org.apache.maven:maven-core:3.9.8", "org.apache.maven", "maven-core", "3.9.8", 1718267050000L);
        final var actual = JSON.std.beanFrom(FoundDependency.class, input);
        assertEquals(expected, actual);
    }
}
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this @Giovds. Definitely challenging to have minimal-change implementation for Record deserialization... it is bit fragile to say the least.

**Comment by cowtowncoder** [comment]
Fixed in 2.18 branch for 2.18.2; should be testable with 2.18.2-SNAPSHOT (added a test but just in case).

**Comment by Giovds** [comment]
Awesome work! I’ll give it a swing once I’m able to 💪

**Comment by cowtowncoder** [comment]
Ok: due to code being bit... minimalistic.. I wouldn't be surprised if you couldn't find other problems still. Eagerly awaiting bug reports :)

**Comment by Giovds** [comment]
Somewhat late response. I've been able to test it on my repository. It seems to work as expected. 👍

**Comment by cowtowncoder** [comment]
@Giovds better late than never :)

Thank you for confirmation.
