### ISSUE TITLE
JSONObjectException cannot be caught

### ISSUE THREAD

**Issue by jonyt** [FasterXML/jackson-jr#19]
hi,

I'm trying to create JSON with `String json = JSON.std.asString(map);` but `JSONObjectException` cannot be caught or thrown because `No exception of type JSONObjectException can be thrown; an exception type must be a subclass of Throwable.` From the docs it seems it's indeed a subclass of Object.

**Comment by gvan** [comment]
Because of this problem Android Studio can't compile project. I think problem in .private package. IDE show this word in yellow color and can't get access to any class from this package.
