### ISSUE TITLE
Json fields starting with capital letter is not getting read properly

### ISSUE THREAD

**Issue by ankit-huskerit** [FasterXML/jackson-jr#22]
i'm using jackson-jr in android project.
i'm using this method.
JSON.std.beanFrom(ShortJsonModel.class,  JsonString);

with above method below json works perfectly 
"{"isActive": true,"isDelete": false,"msg": "success","status": 1}"

but this doesn't work at all. All variables in model class are set to null.  
"{"IsActive": true,"IsDelete": false,"Msg": "success","Status": 1}"

any field in "JsonString" that starts with capital letter doesn't parse at all.  am i missing something?

**Comment by cowtowncoder** [comment]
Property names are case-sensitive, and must follow Java Bean naming rules. `Status` is not a valid Bean property name (there is no getter/setter pair that would infer such property).
So this works as expected.
