### ISSUE TITLE
JsonProcessingException cannot be resolved

### ISSUE THREAD

**Issue by kjkrum** [FasterXML/jackson-jr#23]
When using jackson-jr-all-2.5.2.jar in an Android project, Eclipse displays this warning:

> The type com.fasterxml.jackson.jr.private.JsonProcessingException cannot be resolved. It is indirectly referenced from required .class files`

I haven't run into a situation where Jackson Jr. actually tries to use that class, but if it ever did, presumably my app would crash.

**Comment by cowtowncoder** [comment]
I assume this is same as #17, to be addressed shortly.
