### ISSUE TITLE
No default constructor in JSONReader

### ISSUE THREAD

**Issue by gvan** [FasterXML/jackson-jr#33]
I try to create my custom deserializer. As spesified in the documentation I need to extend JSONReader and change the default JSONReader object as follows: 

JSON j = JSON.std.with(new MyJSONReader());

But JSONReader not contains the default constructor.

**Comment by cowtowncoder** [comment]
There is no default constructor because as you see if you look at existing constructors, there are many settings that must be passed via constructor.
You can have a look at method `JSON._defaultReader(...)` to see how these are typically passed.
