### ISSUE TITLE
ProGuard Settings for Jackson-jr

### ISSUE THREAD

**Issue by GulajavaMinistudio** [FasterXML/jackson-jr#35]
Is there anyone know about Proguard settings for Jackson-jr library in Android ?

I have tested mine with this, inside my proguard-rules.pro files .

``` java
-dontwarn com.fasterxml.jackson.**
-keep class com.fasterxml.jackson.** { *; }

-keep class org.codehaus.** { *; }
-keep public class your.class.** {*;}
-keepattributes *Annotation*,EnclosingMethod,Signature
-keepnames class com.fasterxml.jackson.** { *; }
-keepclassmembers class com.fasterxml.jackson.**  { *; }
-keepclassmembernames class com.fasterxml.jackson.**  { *; }
-keepclasseswithmembernames class com.fasterxml.jackson.** { *; }
-keepclasseswithmembers class com.fasterxml.jackson.**  { *; }
```

But none of them success. When i tested APK with proguard turned on, the app cannot parsing JSON correctly. It just produce empty JSON Arrays , like [{},{},....]

**Comment by cowtowncoder** [comment]
I think you should ask on `jackson-user` list. Only small number of developers follow issue tracker updates, and I would guess there are many more Android developers on the list than within core dev team.

I don't know the answer to this myself.

**Comment by Caerbannog** [comment]
Here is a discussion about the proguard rules for Jackson2: https://github.com/krschultz/android-proguard-snippets/pull/132
