### ISSUE TITLE
Update Jackson Jr Retrofit 2 Converter for Retrofit 2.0.0

### ISSUE THREAD

**Issue by GulajavaMinistudio** [FasterXML/jackson-jr#37]
There are some API changes in Retrofit 2 API in Converter.Factory class and OkHttp 3.
And we have create some gist to fix it , based on existing jackson jr retrofit 2 converter .
And it required Retrofit 2 Beta 4 or newer to use it.

Jackson Jr Converter Class
https://gist.github.com/GulajavaMinistudio/ff7d958b58ddac9049cd

Jackson Jr Request Body Converter Class
https://gist.github.com/GulajavaMinistudio/427b88c0a78845f775de

JacksonJrResponseArrayConverter class for converting JSON Array to List<Pojo>
https://gist.github.com/GulajavaMinistudio/ad6a1b04095c182a3f4b

JacksonJrResponseConverter class for converting JSON to JSON Object POJO
https://gist.github.com/GulajavaMinistudio/11e3900e1b0b6590ee3e

Hope it can help

**Comment by cowtowncoder** [comment]
Thank you -- I updated code as suggested, will be included in 2.7.3.
