### ISSUE TITLE
How to deal with JSON produced by Jackson's Object Identity feature?

### ISSUE THREAD

**Issue by gpiancastelli** [FasterXML/jackson-jr#39]
What is the correct way to deal with JSON received from a service that uses Jackson to encode with its Object Identity feature activated? This would be JSON where some of the objects are replaced by an identifier, usually a number that is included as the value of an `@id` property in the original object. The feature is typically used to avoid cycles or duplication in the JSON object graphs. For example:

```
{
    "@id" : 1,
    "value" : 13,
    "next" : {
       "@id" : 2,
       "value" : 42,
       "next" : 1
     }
  }
```

The `next` property of the enclosed object points to the outer object, by means of the `1` identifier, which is the value of the `@id` property of the outer object.

When I try to deserialize such an object with Jackson Jr., I receive an error about a missing constructor with a single parameter of type long. However, I don't see how such a constructor could be helpful in this case: even having Jackson Jr. lending the identifier to the constructor, how could the right object be extracted from JSON using that identifier?

I wonder if Jackson Jr. is capable to automatically produce the proper object graph by parsing such JSON data. Should I resort to bring the full Jackson library in my Android application in order to correctly deal with the Object Identity feature?

**Comment by cowtowncoder** [comment]
Yes, to resolve object ids either use of full jackson-databind makes sense, or binding to intermediate form, resolving manually deps -- but in the end that may not be simpler than using databind.

**Comment by cowtowncoder** [comment]
Not much that can be done here: to handle Identity Id that full Jackson creates, you need full Jackson; support for jackson-jr unlikely to ever be added.
I am open to smaller improvements that would maybe allow handling these in some way, but such request would need to be more specific.
