### ISSUE TITLE
Cannot read empty or singleton arrays with JSON.arrayOfFrom

### ISSUE THREAD

**Issue by gpiancastelli** [FasterXML/jackson-jr#40]
When I write:

    JSON.std.with(JSON.Feature.READ_JSON_ARRAYS_AS_JAVA_ARRAYS)
            .arrayOfFrom(MyClass.class, stringContent);

my application crashes with a `ClassCastException`:

    java.lang.ClassCastException: java.lang.Object[] cannot be cast to com.example.MyClass[]

Everything works when the array carries more than one element. I have also tested with empty arrays, and I got the same exception. I am somehow reminded of #27 where arrays featured a similarly bugged behaviour, except it involved casting an `ArrayList`.

**Comment by cowtowncoder** [comment]
Sounds like a bug: thank you for reporting this.

**Comment by cowtowncoder** [comment]
Thank you for reporting this, was a quick fix. Will be in 2.6.6 and 2.7.4.
