### ISSUE TITLE
How to avoid cycles while serializing an object graph to JSON?

### ISSUE THREAD

**Issue by gpiancastelli** [FasterXML/jackson-jr#41]
Is there a way to avoid cycles while serializing an object graph to JSON, akin to the Object Identity feature of the full Jackson package?

**Comment by cowtowncoder** [comment]
No: Jackson-jr does not have (or is meant to have) more advanced features at this point. So your best bet is full `jackson-databind`.

**Comment by cowtowncoder** [comment]
Bit of additional context: to be able to detect cyclic serialization, it would be necessary to have a stack of nested Objects to see if there is a reference back to something `JSONWriter` was already serializing.
Typically this is done within a context object passed along the call stack. Unfortunately `JSONWriter` has no such context object; handling is kept to minimum. So this state tracking would have to be added, and that is sizable and intrusive change, This is why I am not very optimistic about this being something to support here.

**Comment by gpiancastelli** [comment]
Thanks for the info. I did already guess that no Object Identity / cycle detection feature was available in Jackson Jr., but I just wanted to be sure and needed someone to confirm that. I understand the rationale both for keeping the library small and for avoiding changes with a big impact on its general architecture. I'll have a shot at full Jackson and see how it goes.

**Comment by cowtowncoder** [comment]
@gpiancastelli yes no prob and it does make sense to ask instead of assume. Also, I am open to improvement ideas within (much) small(er) scope; for example, with perhaps some amount of configuration for naming, ignoral of properties.

Also thank you for your bug report wrt array reader.

**Comment by cowtowncoder** [comment]
No current plans to support this; a new issue can be filed for specific ask ("allow detecting cycles" , for example)
