### ISSUE TITLE
Shading behavior of `jackson-jr-all` is surprising.

### ISSUE THREAD

**Issue by adamv** [FasterXML/jackson-jr#42]
In this repo: https://github.com/adamv/jr-shade

I'm including `jackson-jr-all` as a dependency, and shading it so that neither it nor `jackson-core` leak downstream. When do `mvn package`, then unzip the resulting fat jar I see two copies of `jackson-core`, one shaded one unshaded (which I think it is picking up through the parent pom?)

To get a properly shaded library I need to exclude the `jackson-core` dependency:
https://github.com/adamv/jr-shade/blob/master/pom.xml#L51

I'm not sure if this is expected behavior or not. If so, it would be helpful for this project to document the maven dependency w/ the exclusion included.

**Comment by cowtowncoder** [comment]
Obviously the goal is for there to only be shaded copy, and that no dependency would be leaked.

You may be right about parent pom -- dependency does not really belong there, just dependencyManagement section. I'll change that. Would be it easy for you to see that 2.7.5-SNAPSHOT  behaves better?

**Comment by adamv** [comment]
Is there a maven repo I can use to pull down the SNAPSHOT, or is the best course of action to compile & install locally?

**Comment by adamv** [comment]
Checked out sources locally, `2.7.5-SNAPSHOT` appears to have corrected this. Thanks!

**Comment by cowtowncoder** [comment]
I did `mvn deploy` so hopefully it goes to Sonatype Maven also. Thank you for reporting this & verifying!
