### ISSUE TITLE
Duplicate key detection does not work

### ISSUE THREAD

**Issue by inorick** [FasterXML/jackson-jr#50]
The feature flag `FAIL_ON_DUPLICATE_MAP_KEYS` does not seem to work. As I understand the parser configuration, the following code should throw an exception but doesnt:
```
String duplicateKeyString = "{\"a\":1,\"b\":2,\"b\":3,\"c\":4}";`
Map<Object, Object> json = JSON.std
.with(JSON.Feature.FAIL_ON_DUPLICATE_MAP_KEYS)
.mapFrom(duplicateKeyString);
```

The same is true for this similar call:
```
JSON.std.with(new JacksonJrsTreeCodec())
.with(JSON.Feature.FAIL_ON_DUPLICATE_MAP_KEYS)
.treeFrom(duplicateKeyString);
```

**Comment by cowtowncoder** [comment]
Definitely sounds like a bug yes. Which version?

**Comment by inorick** [comment]
I tested 2.8.8 and 2.9.0.pr2

**Comment by cowtowncoder** [comment]
@inorick thank you! Just wanted to verify; I occasionally get reports against versions so old that problem has been fixed.

**Comment by cowtowncoder** [comment]
Lol. Feature added originally, never implemented. Obviously also not tested. Should do both.

**Comment by inorick** [comment]
Hehe, thanks. I really like the 'jr' flavour of jackson and the whole idea behind it. This is really the last thing I miss :)

**Comment by cowtowncoder** [comment]
@inorick Thank you for reporting this; fixed. Please let me know if and when you find other edge cases; as I said testing coverage is bit lighter than it should be.

Fix will be in 2.8.9 / 2.9.0.pr3.

Also: appreciate feedback; it is hard to know which things are useful -- seemed to me too that light-weight variant like jr would make lots of sense for many use cases. So I'm happy others find it useful too!

**Comment by inorick** [comment]
Thanks, that was quick!
Sure, I plan to use jr more anyway and will report back if I encounter anything.

**Comment by inorick** [comment]
I have to reopen the issue: The function `JSON.treeFrom()` still ignores the feature.
The following test case fails in git master:

```
public void testFailOnDupMapKeys() throws Exception
    {
        JSON j = JSON.std.with(new JacksonJrsTreeCodec()).with(JSON.Feature.FAIL_ON_DUPLICATE_MAP_KEYS);
        assertTrue(j.isEnabled(JSON.Feature.FAIL_ON_DUPLICATE_MAP_KEYS));
        assertNotNull(j.getTreeCodec());
        final String json = "{\"a\":1,\"b\":2,\"b\":3,\"c\":4}";
        try {
            /*Map<?,?> map =*/ j.treeFrom(json);
            fail("Should not pass");
        } catch (JSONObjectException e) {
            verifyException(e, "Duplicate key");
        }
    }
```

**Comment by cowtowncoder** [comment]
@inorick Technically this is out of scope of setting, as it relates to `java.util.Map` keys, not tree keys ("Object" node). But I guess it would be reasonable to extend the definition. I'll open a new issue for that part.
(also: while a new feature could be added, probably no need as cases do not overlap).
