### ISSUE TITLE
Broken dependency  com.fasterxml.jackson.jr:jackson-jr-objects:2.6.7

### ISSUE THREAD

**Issue by stokito** [FasterXML/jackson-jr#52]
Hello,
I tried to include a dependency of [com.fasterxml.jackson.jr:jackson-jr-objects:2.6.7](http://search.maven.org/#artifactdetails%7Ccom.fasterxml.jackson.core%7Cjackson-databind%7C2.6.7%7Cbundle) to my project, but Maven failed to resolve it with error:
```
[ERROR] Failed to execute goal on project geoip2: Could not resolve dependencies for project com.maxmind.geoip2:geoip2:jar:2.9.1-SNAPSHOT: Failed to collect dependencies at com.fasterxml.jackson.jr:jackson-jr-objects:jar:2.6.7: Failed to read artifact descriptor for com.fasterxml.jackson.jr:jackson-jr-objects:jar:2.6.7: Could not find artifact com.fasterxml.jackson.jr:jackson-jr-parent:pom:2.6.7 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

It looks like Maven tries to resolve dependency to com.fasterxml.jackson.jr:jackson-jr-parent:pom:2.6.7 which is doesn't deployed to Maven Central http://repo1.maven.org/maven2/com/fasterxml/jackson/jr/jackson-jr-parent/2.6.7/jackson-jr-parent-2.6.7.pom

In the same time the artifact for com.fasterxml.jackson.jr:jackson-jr-objects:2.8.8 is deployed correctly http://repo1.maven.org/maven2/com/fasterxml/jackson/jr/jackson-jr-parent/2.8.8/jackson-jr-parent-2.8.8.pom
That's why I can use in my project dependency jackson-jr-objects:2.8.8 but can't 2.6.7.

I need v2.6.7 because it works on JDK6.

Could you please fix that and deploy jackson-jr-parent-2.6.7.pom?

**Comment by cowtowncoder** [comment]
@stokito It does look like Maven Central has broken parent for 2.6.7
This has been constant (if rare) pain with MC, maven release plug-in: sometimes, for some reason (or without one) one of artifacts fails, without client indicating problem.

I'll see if re-release works when I get to it (I don't have access to do it right now).

Thank you for reporting the issue.

**Comment by cowtowncoder** [comment]
Pushed `2.6.7` of parent.
