### ISSUE TITLE
`java.io.File` is not a valid source for anyFrom()/mapFrom()

### ISSUE THREAD

**Issue by CoreyTeffetalor** [FasterXML/jackson-jr#53]
I'm getting an exception when attempting to use mapFrom/anyFrom in gradle/groovy:

`com.fasterxml.jackson.jr.ob.JSONObjectException: Can not use Source of type java.io.File as input (use an InputStream, Reader, String, byte[], File or URL`

Thrown here: https://github.com/FasterXML/jackson-jr/blob/master/jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/JSON.java#L1064

It looks like the cases above don't handle `java.io.File` as the documentation/exception claims.

**Comment by cowtowncoder** [comment]
Sounds like a bug really; thank you for reporting this.

**Comment by CoreyTeffetalor** [comment]
Thanks for the quick resolution!

**Comment by cowtowncoder** [comment]
@CoreyTeffetalor np, thank you for reporting it. It was an odd omission, considering javadocs. But it's part of API that it easy to miss since there isn't much to test beyond existence (since underlying functionality after construction of input stream does not differ).
