### ISSUE TITLE
Add `Json.mapOfFrom(Class)` to support binding POJO-valued maps

### ISSUE THREAD

**Issue by ocind** [FasterXML/jackson-jr#66]
Hi 'm wondering if Map<String, POJO> deserialization is currently supported by jackson-jr.
As far as I see, there is only `mapFrom` which returns Map<T,Object>

**Comment by cowtowncoder** [comment]
Currently it is not supported and references to `Map` mean "untyped".

But since there actually is `listOfFrom()`, we could quite easily have `mapOfFrom()` to do this -- would that make sense? I think I could probably add this in 2.10, to be available relatively soon.

**Comment by ocind** [comment]
@cowtowncoder whoa! that's really fast! Thank you @cowtowncoder for the awesome work!!!

**Comment by cowtowncoder** [comment]
Lucky timing :)

But thank you for pointing out the missing part -- it happened to be easy to add, too, given existing `listOfFrom()`. I am happy to get a few improvements in 2.10, to make `jackson-jr` much more useful: now one can add custom `ValueReader` s and `ValueWriter`s too, opening door to 3rd party datatypes as well.
