### ISSUE TITLE
Public static fields are included in serialized output

### ISSUE THREAD

**Issue by MikeDombo** [FasterXML/jackson-jr#84]
Public static fields are included in the serialized output, is this the proper behavior? I know that I can `@JsonIgnore` them, but this is not the same as jackson-databind so I'm wondering if this is actually a bug.

**Comment by cowtowncoder** [comment]
Yes, that would be a bug. Static fields should NOT be included.

... my only fear is that someone, somewhere, might be counting on that as "feature". :-(

If it is easy enough to do, adding a new `Feature` to allow static fields (but defaulting, for 2.13, for "don't include") might make sense.

**Comment by MikeDombo** [comment]
Resolved by #86
