### ISSUE TITLE
Make `jr-stree` dependency to `jr-objects` optional

### ISSUE THREAD

**Issue by yawkat** [FasterXML/jackson-jr#88]
stree doesn't really have a reason to depend on jr-objects. The only dependency is in `JrSimpleTreeExtension`.

Because there are already no other code dependencies in the jr-stree module, users can already add an exclusion for the jr-objects artifact and jr-stree will still work fine. However, this approach doesn't guarantee that it'll keep working in the future.

Making the dependency to jr-objects optional in the pom.xml would be better. It is technically a breaking change for users that only depend on jr-stree but still use jr-objects, but this is not an issue in my opinion. It's still not something that should appear in a patch release, but it would be fine for 2.13 (unless it's too late for that now?).

Thoughts?

**Comment by cowtowncoder** [comment]
Hmmh. Interesting. Did not quite realize that there is no real dependency.

So, +1 for removing dependency from 2.13 -- I think that while it might cause an issue for someone, it seems like the right thing to do conceptually.

If you have time to do PR against 2.13, including a note on README(s?), that'd be good. I can then update 2.13 release notes with the info.

**Comment by cowtowncoder** [comment]
Oh nm wrt PR, saw your other note. I'll work on this on my own, seems simple enough.

**Comment by yawkat** [comment]
Thanks! It should just be an optional dep.

**Comment by cowtowncoder** [comment]
Ah. Somehow I missed what you mentioned, class `JrSimpleTreeExtension` when grepping (and not reading the description well).
That was the reason for adding dependency. But marking it as `optional` does seem like a reasonable idea.
I guess `provided` could also work but maybe optional is better way.
