### ISSUE TITLE
`module-info.java` of `jr-stree` refers to module `com.fasterxml.jackson.jr.ob.api`, which is not defined

### ISSUE THREAD

**Issue by qurben** [FasterXML/jackson-jr#98]
`module-info.java` in jr-stree requires `com.fasterxml.jackson.jr.ob.api`, but this module does not exist, this package _is_ exported by `com.fasterxml.jackson.jr.ob`, but that doesn't mean it is required to explicitly require this package.

**Comment by cowtowncoder** [comment]
I don't quite understand the problem here: that package is exposed by `jr-objects` and as name suggests contains API types for that module. Stree module needs it. What is not defined? What should be changed?

**Comment by qurben** [comment]
`jr-stree` should only require the `com.fasterxml.jackson.jr.ob` module, this implies access to the `api` package (because this module exports the `api` package).

`require` is for requiring _modules_, not _packages_.

The error I'm getting is 

```
'java.lang.module.FindException: Module com.fasterxml.jackson.jr.ob.api not found, required by com.fasterxml.jackson.jr.stree'.
```

**Comment by cowtowncoder** [comment]
Ahh. Ok yes. I.... have not used module system for anything myself and forgot the asymmetry (exporting package, requiring modules).
